version: '3'

services:
  app:
    build:
      context: .
    image: ecologicaldesign:local
    container_name: ecodesign
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./src:/app/src
      - ./lib:/app/lib
      - ./utils:/app/utils
      - ./log:/app/log
    env_file: 
      - .env
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: ecodesign-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    restart: unless-stopped

volumes:
  mongodb_data:
