version: '3'

services:
  app:
    build:
      context: .
    image: ecologicaldesign:local
    container_name: ecodesign
    # Bỏ port 5000 vì sẽ sử dụng Nginx làm reverse proxy
    # ports:
    #   - "5000:5000"
    expose:
      - "5000"
    volumes:
      - ./app:/app/app
      - ./src:/app/src
      - ./lib:/app/lib
      - ./utils:/app/utils
      - ./log:/app/log
    env_file: 
      - .env
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: ecodesign-nginx
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - app
    restart: unless-stopped
    volumes:
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./app/static:/app/app/static
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: ecodesign-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
