version: '3'

services:
  app:
    build:
      context: .
    image: ecologicaldesign:local
    container_name: ecodesign
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./src:/app/src
      - ./lib:/app/lib
      - ./utils:/app/utils
      - ./log:/app/log
    env_file: 
      - .env
    restart: unless-stopped
